# Generated by Django 5.0.14 on 2026-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0008_farm_riskradardata'),
    ]

    operations = [
        migrations.AddField(
            model_name='authotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset_password', 'Reset Password')], default='login', max_length=32),
        ),
    ]
