# Generated by Django 5.0.14 on 2026-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0010_backfill_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register')], default='login', max_length=32),
        ),
    ]
