# Generated by Django 5.0.14 on 2026-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi_core', '0011_alter_authotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
